# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          # echo Add other actions to build,
          # echo test, and deploy your project.
          ls -la
          # kubectl apply -f hello_deployment_gh.yaml
          kubectl apply -f hello_service_gh.yaml

